theme: jekyll-theme-minimal
title: Wang Yan
logo: /zhengjianzhao.jpg
description: The personal website of Wang Yan.

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false
